dist: bionic
sudo: required
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install pytest coveralls
- pip install .
script:
- coverage run --source=s2reader setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  tag_name: $TRAVIS_TAG
  user: __token__
  password: $TEST_PYPI_TOKEN
  on:
    branch: master
    repo: robert-werner/s2reader3
